-- MySQL Script generated by MySQL Workbench
-- Wed May  4 19:11:27 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stock` ;

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stock` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `stock` ;

-- -----------------------------------------------------
-- Table `stock`.`stock_year_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`stock_year_report` ;

CREATE TABLE IF NOT EXISTS `stock`.`stock_year_report` (
  `report_id` VARCHAR(36) NOT NULL,
  `stock_code` VARCHAR(45) NOT NULL,
  `publish_time` DATETIME NOT NULL,
  `report_name` VARCHAR(255) NOT NULL,
  `pdf_url` VARCHAR(255) NOT NULL,
  `pdf_path` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`report_id`),
  INDEX `index_stock_code` (`stock_code` ASC),
  INDEX `index_publish_time` (`publish_time` ASC),
  INDEX `index_report_name` (`report_name` ASC),
  UNIQUE INDEX `unique_pdf_path` (`pdf_path` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
