-- MySQL Script generated by MySQL Workbench
-- Thu May  5 11:24:44 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stock` ;

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stock` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `stock` ;

-- -----------------------------------------------------
-- Table `stock`.`stock_year_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`stock_year_report` ;

CREATE TABLE IF NOT EXISTS `stock`.`stock_year_report` (
  `report_id` VARCHAR(36) NOT NULL,
  `stock_code` VARCHAR(45) NOT NULL,
  `publish_time` DATETIME NOT NULL,
  `report_name` VARCHAR(255) NOT NULL,
  `pdf_url` VARCHAR(255) NOT NULL,
  `pdf_path` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`report_id`),
  INDEX `index_stock_code` (`stock_code` ASC),
  INDEX `index_publish_time` (`publish_time` ASC),
  INDEX `index_report_name` (`report_name` ASC),
  UNIQUE INDEX `unique_pdf_path` (`pdf_path` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`stock_company_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`stock_company_info` ;

CREATE TABLE IF NOT EXISTS `stock`.`stock_company_info` (
  `stock_code` VARCHAR(45) NOT NULL,
  `stock_name` VARCHAR(255) NULL,
  `gsqc` VARCHAR(255) NULL,
  `ywmc` VARCHAR(255) NULL,
  `zcdz` VARCHAR(255) NULL,
  `gsjc` VARCHAR(255) NULL,
  `fddbr` VARCHAR(255) NULL,
  `gsdm` VARCHAR(255) NULL,
  `zczb` VARCHAR(255) NULL,
  `hyzl` VARCHAR(255) NULL,
  `yzbm` VARCHAR(255) NULL,
  `gsdh` VARCHAR(255) NULL,
  `gscz` VARCHAR(255) NULL,
  `gswz` VARCHAR(255) NULL,
  `sssj` VARCHAR(255) NULL,
  `zgsj` VARCHAR(255) NULL,
  `fxsl` VARCHAR(255) NULL,
  `fxjg` VARCHAR(255) NULL,
  `fxsyl` VARCHAR(255) NULL,
  `fxfs` VARCHAR(255) NULL,
  `zcxs` VARCHAR(255) NULL,
  `shtjr` VARCHAR(255) NULL,
  `bjjg` VARCHAR(255) NULL,
  PRIMARY KEY (`stock_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`stock_balancesheet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`stock_balancesheet` ;

CREATE TABLE IF NOT EXISTS `stock`.`stock_balancesheet` (
  `stock_code` VARCHAR(45) NOT NULL,
  `publish_time` VARCHAR(45) NOT NULL,
  `stock_name` VARCHAR(255) NULL,
  `data` TEXT NULL,
  PRIMARY KEY (`stock_code`, `publish_time`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`stock_cashflow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`stock_cashflow` ;

CREATE TABLE IF NOT EXISTS `stock`.`stock_cashflow` (
  `stock_code` VARCHAR(45) NOT NULL,
  `publish_time` VARCHAR(45) NOT NULL,
  `stock_name` VARCHAR(255) NULL,
  `data` TEXT NULL,
  PRIMARY KEY (`stock_code`, `publish_time`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`stock_income`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`stock_income` ;

CREATE TABLE IF NOT EXISTS `stock`.`stock_income` (
  `stock_code` VARCHAR(45) NOT NULL,
  `publish_time` VARCHAR(45) NOT NULL,
  `stock_name` VARCHAR(255) NULL,
  `data` TEXT NULL,
  PRIMARY KEY (`stock_code`, `publish_time`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
