# -*- coding: utf-8 -*-

import re

from scrapy import Spider, Request
from scrapy.linkextractors import LinkExtractor

from spider.loader.loaders import (
    ChinaCloudNewsLoader,
    Kn58NewsLoader,
    YnetNewsLoader,
    LeiphoneNewsLoader,
    SapNewsLoader,
    CniiComCnNewsLoader,
    CctimeNewsLoader,
    WWW163NewsLoader,
    ChinaComCnNewsLoader,
    CSDNBlogLoader,
    VsharingNewsLoader,
    ChinaNewsLoader,
    It168NewsLoader,
    N36dsjNewsLoader,
    SinaNewsLoader,
    N100ecNewsLoader,
    SootooNewsLoader,
    PcpopNewsLoader,
    CSDNNewsLoader,
    ZJOLComCnNewsLoader,
    ENorthNewsLoader,
    XinhuanetNewsLoader,
    CnsoftNewsLoader,
    TechwebNewsLoader,
    SohuNewsLoader,
    IdcNewsLoader,
    CqNewsNetNewsLoader,
    QQNewsLoader,
    CeocioNewsLoader,
    ChinabyteNewsLoader,
    YeskyComNewsLoader,
    ZdnetNewsLoader,
    TopointNewsLoader,
    CcwNewsLoader,
    PeopleComCnNewsLoader,
    QudongNewsLoader,
    CiotimesNewsLoader,
    CaijingNewsLoader,
    DataTsciComCnNewsLoader,
    YCWBNewsLoader,
    CbismbNewsLoader,
    YidonghuaNewsLoader,
    HexunNewsLoader,
    DataguruNewsLoader,
    EastDayNewsLoader,
    GmwNewsLoader,
    SPNComNewsLoader,
    EworksNewsLoader,
    CcidnetNewsLoader,
    CbinewsNewsLoader,
    S3d4NewsLoader,
    N199itNewsLoader,
    CtocioNewsLoader,
    IFengNewsLoader,
    ZolNewsLoader,
    QianLongNewsLoader
)


class UradarUrlSpider(Spider):

    u"""UradarUrl爬虫
    爬虫内注册(url的正则表达式,Item的Loader类)，对匹配的url进行item解析，
    响应中所有的url都返回一个请求
    """

    name = 'uradar_url'

    start_urls = [
        'http://www.it168.com/',
        'http://data.tsci.com.cn/',
        'http://www.qudong.com/',
        'http://www.kn58.com/',
        'http://csdn.net',
        'http://app.myzaker.com/',
        'http://csdn.net',
        'http://www.techweb.com.cn/',
        'http://www.cnsoftnews.com/',
        'http://www.ctocio.com/',
        'http://www.100ec.cn',
        'http://www.163.com/',
        'http://www.199it.com/',
        'http://qq.com',
        'http://www.cnii.com.cn/',
        'http://www.leiphone.com/',
        'http://huiyi.csdn.net/',
        'http://www.zol.com.cn/',
        'http://toutiao.com/',
        'http://www.e-works.net.cn/',
        'http://www.sootoo.com/',
        'http://www.vsharing.com/',
        'http://www.people.com.cn/',
        'http://www.163.com/',
        'http://www.huxiu.com/',
        'http://www.zjol.com.cn/',
        'http://www.idc.com.cn/',
        'http://www.eastday.com/',
        'http://www.caijing.com.cn/',
        'http://www.ccidnet.com/',
        'http://chinabyte.com/',
        'http://www.ciotimes.com/',
        'http://xinhuanet.com/',
        'http://www.china.com.cn/',
        'http://www.pcpop.com/',
        'http://global.sap.com/china/news-reader/index.epx',
        'http://www.spn.com.cn/',
        'http://www.enorth.com.cn/',
        'http://www.100ec.cn',
        'http://www.cbinews.com',
        'http://www.36dsj.com/',
        'http://www.sina.com.cn',
        'http://www.ycwb.com/',
        'http://cbismb.com/',
        'http://gmw.cn/',
        'http://www.sohu.com/',
        'http://www.china.com/index.html',
        'http://www.ccw.com.cn/',
        'http://www.cqnews.net/',
        'http://www.china-cloud.com/',
        'http://www.yidonghua.com',
        'http://dataguru.cn/',
        'http://s3d4.cn/',
        'http://www.topoint.com.cn/',
        'http://www.cctime.com/',
        'http://www.zdnet.com.cn',
        'http://www.ynet.com/',
        'http://www.hexun.com/',
        'http://www.yesky.com/',
        'http://www.qianlong.com/',
        'http://www.ifeng.com',
        'http://www.ceocio.com.cn/',
        'http://www.it168.com/',
        'http://data.tsci.com.cn/',
        'http://www.qudong.com/',
        'http://www.kn58.com/',
        'http://csdn.net',
        'http://app.myzaker.com/',
        'http://csdn.net',
        'http://www.techweb.com.cn/',
        'http://www.cnsoftnews.com/',
        'http://www.ctocio.com/',
        'http://www.100ec.cn',
        'http://www.163.com/',
        'http://www.199it.com/',
        'http://qq.com',
        'http://www.cnii.com.cn/',
        'http://www.leiphone.com/',
        'http://huiyi.csdn.net/',
        'http://www.zol.com.cn/',
        'http://toutiao.com/',
        'http://www.e-works.net.cn/',
        'http://www.sootoo.com/',
        'http://www.vsharing.com/',
        'http://www.people.com.cn/',
        'http://www.163.com/',
        'http://www.huxiu.com/',
        'http://www.zjol.com.cn/',
        'http://www.idc.com.cn/',
        'http://www.eastday.com/',
        'http://www.caijing.com.cn/',
        'http://www.ccidnet.com/',
        'http://chinabyte.com/',
        'http://www.ciotimes.com/',
        'http://xinhuanet.com/',
        'http://www.china.com.cn/',
        'http://www.pcpop.com/',
        'http://global.sap.com/china/news-reader/index.epx',
        'http://www.spn.com.cn/',
        'http://www.enorth.com.cn/',
        'http://www.100ec.cn',
        'http://www.cbinews.com',
        'http://www.36dsj.com/',
        'http://www.sina.com.cn',
        'http://www.ycwb.com/',
        'http://cbismb.com/',
        'http://gmw.cn/',
        'http://www.sohu.com/',
        'http://www.china.com/index.html',
        'http://www.ccw.com.cn/',
        'http://www.cqnews.net/',
        'http://www.china-cloud.com/',
        'http://www.yidonghua.com',
        'http://dataguru.cn/',
        'http://s3d4.cn/',
        'http://www.topoint.com.cn/',
        'http://www.cctime.com/',
        'http://www.zdnet.com.cn',
        'http://www.ynet.com/',
        'http://www.hexun.com/',
        'http://www.yesky.com/',
        'http://www.qianlong.com/',
        'http://www.ifeng.com',
        'http://www.ceocio.com.cn/'
    ]

    allowed_domains = [
        'it168.com',
        'data.tsci.com.cn',
        'qudong.com',
        'kn58.com',
        'csdn.net',
        'app.myzaker.com',
        'csdn.net',
        'techweb.com.cn',
        'cnsoftnews.com',
        'ctocio.com',
        '100ec.cn',
        '163.com',
        '199it.com',
        'qq.com',
        'weixin.sogou.com',
        'mp.weixin.qq.com',
        'cnii.com.cn',
        'leiphone.com',
        'csdn.net',
        'zol.com.cn',
        'toutiao.com',
        'e-works.net.cn',
        'sootoo.com',
        'vsharing.com',
        'people.com.cn',
        '163.com',
        'huxiu.com',
        'zjol.com.cn',
        'idc.com.cn',
        'eastday.com',
        'caijing.com.cn',
        'ccidnet.com',
        'chinabyte.com',
        'ciotimes.com',
        'xinhuanet.com',
        'china.com.cn',
        'pcpop.com',
        'global.sap.com',
        'spn.com.cn',
        'enorth.com.cn',
        '100ec.cn',
        'cbinews.com',
        '36dsj.com',
        'sina.com.cn',
        'ycwb.com',
        'cbismb.com',
        'gmw.cn',
        'sohu.com',
        'china.com',
        'ccw.com.cn',
        'cqnews.net',
        'china-cloud.com',
        'yidonghua.com',
        'gartner.com',
        'dataguru.cn',
        's3d4.cn',
        'topoint.com.cn',
        'cctime.com',
        'zdnet.com.cn',
        'ynet.com',
        'hexun.com',
        'yesky.com',
        'qianlong.com',
        'ifeng.com',
        'ceocio.com.cn',
        'it168.com',
        'data.tsci.com.cn',
        'qudong.com',
        'kn58.com',
        'csdn.net',
        'app.myzaker.com',
        'csdn.net',
        'techweb.com.cn',
        'cnsoftnews.com',
        'ctocio.com',
        '100ec.cn',
        '163.com',
        '199it.com',
        'qq.com',
        'weixin.sogou.com',
        'mp.weixin.qq.com',
        'cnii.com.cn',
        'leiphone.com',
        'csdn.net',
        'zol.com.cn',
        'toutiao.com',
        'e-works.net.cn',
        'sootoo.com',
        'vsharing.com',
        'people.com.cn',
        '163.com',
        'huxiu.com',
        'zjol.com.cn',
        'idc.com.cn',
        'eastday.com',
        'caijing.com.cn',
        'ccidnet.com',
        'chinabyte.com',
        'ciotimes.com',
        'xinhuanet.com',
        'china.com.cn',
        'pcpop.com',
        'global.sap.com',
        'spn.com.cn',
        'enorth.com.cn',
        '100ec.cn',
        'cbinews.com',
        '36dsj.com',
        'sina.com.cn',
        'ycwb.com',
        'cbismb.com',
        'gmw.cn',
        'sohu.com',
        'china.com',
        'ccw.com.cn',
        'cqnews.net',
        'china-cloud.com',
        'yidonghua.com',
        'gartner.com',
        'dataguru.cn',
        's3d4.cn',
        'topoint.com.cn',
        'cctime.com',
        'zdnet.com.cn',
        'ynet.com',
        'hexun.com',
        'yesky.com',
        'qianlong.com',
        'ifeng.com',
        'ceocio.com.cn'
    ]

    matcher_loader_dict = {
        re.compile('s3d4\.cn/news/\d+'): S3d4NewsLoader(),
        re.compile('caijing\.com\.cn/\d{8}/\d+\.shtml'): CaijingNewsLoader(),
        re.compile('leiphone\.com/news/\d{6}/\S+\.html'): LeiphoneNewsLoader(),
        re.compile('http://www.vsharing.com/\w+/\w+/\d{4}-\d+/\d+.html'): VsharingNewsLoader(),
        re.compile('36dsj\.com/archives/\d+'): N36dsjNewsLoader(),
        re.compile('ctocio\.com/ccnews/\d+\.html'): CtocioNewsLoader(),
        re.compile('news\.ynet\.com/[\d\.]+/\d{4}/\d{2}/\d+\.html'): YnetNewsLoader(),
        re.compile('\w+\.ycwb.com/\d{4}-\d{2}/\d+/\w+.htm'): YCWBNewsLoader(),
        re.compile('pcpop\.com/doc/\d+/\d+/\d+\.shtml'): PcpopNewsLoader(),
        re.compile('data\.tsci\.com\.cn/News/NewsShow\.aspx\?NewsId=\d+'): DataTsciComCnNewsLoader(),
        re.compile('cq\.cqnews\.net/\S+/\d{4}-\d{2}/\d{2}/content_\d+.htm'): CqNewsNetNewsLoader(),
        re.compile('it168\.com/a\d{4}/\d{4}/\d+/\d+\.shtml'): It168NewsLoader(),
        re.compile('zol\.com\.cn/\d+/\d+\.html'): ZolNewsLoader(),
        re.compile('\w+\.eastday.com/\w+/\d{8}/\w+.html'): EastDayNewsLoader(),
        re.compile('kn58\.com/.*/detail_\d{4}_\d{4}/\d+\.html'): Kn58NewsLoader(),
        re.compile('100ec\.cn/detail--\d+\.html'): N100ecNewsLoader(),
        re.compile('http://www.spn.com.cn/\w+/\d+/\d+.html'): SPNComNewsLoader(),
        re.compile('.*?sina\.com\.cn/\d{4}-\d{2}-\d{2}/\d+.html'): SinaNewsLoader(),
        re.compile('.*?sina\.com\.cn/\S+?/\d{4}-\d{2}-\d{2}/doc-\S+\.shtml'): SinaNewsLoader(),
        re.compile('http://blog.csdn.net/\S+?/article/details/\d+'): CSDNBlogLoader(),
        re.compile('199it\.com/archives/\d+\.html'): N199itNewsLoader(),
        re.compile('http://www.sootoo.com/content/\d+.shtml'): SootooNewsLoader(),
        re.compile('news\.xinhuanet\.com/\S+/\d{4}-\d{2}/\d{2}/c_\d+.htm'): XinhuanetNewsLoader(),
        re.compile('.*china/news-reader/index\.epx\?.*articleID=\d+.*'): SapNewsLoader(),
        re.compile('ceocio\.com\.cn/.*/\d{4}-\d{2}-\d{2}/\d+\.shtml'): CeocioNewsLoader(),
        re.compile('ccidnet\.com/\d{4}/\d{4}/\d+\.shtml'): CcidnetNewsLoader(),
        re.compile('zdnet\.com\.cn/.*/\d{4}/\d{4}/\d+\.shtml'): ZdnetNewsLoader(),
        re.compile('cctime\.com/html/\d{4}-\d{1,2}-\d{1,2}/\d+\.htm'): CctimeNewsLoader(),
        re.compile('article/\d{4}-\d{2}-\d{2}/\d+'): CSDNNewsLoader(),
        re.compile('dataguru\.cn/article-\d+-\d+\.html'): DataguruNewsLoader(),
        re.compile('\w+\.zjol.com.cn/\w+/\d{4}/\d{2}/\d{2}/\d+.shtml'): ZJOLComCnNewsLoader(),
        re.compile('\w+\.qianlong.com/\d{4}/\d{4}/\d{6}\.shtml'): QianLongNewsLoader(),
        re.compile('idc\.com\.cn/about/press\.jsp\?id=\S+'): IdcNewsLoader(),
        re.compile('http://\w+.e-works.net.cn/\w+/\w+.htm'): EworksNewsLoader(),
        re.compile('ciotimes\.com/\S+/\d+\.html'): CiotimesNewsLoader(),
        re.compile('yidonghua\.com/post/\d+\.html'): YidonghuaNewsLoader(),
        re.compile('ifeng\.com/\S+?/\d{8}/\d+_\d{1}.shtml'): IFengNewsLoader(),
        re.compile('china\.com\.cn/\d{4}-\d{2}/\d{2}/content_\d+\.htm'): ChinaComCnNewsLoader(),
        re.compile('hexun\.com/\d{4}-\d{2}-\d{2}/\d+\.html'): HexunNewsLoader(),
        re.compile('\S+\.163.com/\d{2}/\d{4}/\d+/\S+.html'): WWW163NewsLoader(),
        re.compile('yesky.com/\d+/\d+.shtml'): YeskyComNewsLoader(),
        re.compile('qudong\.com/\d{4}/\d{4}/\d+\.shtml'): QudongNewsLoader(),
        re.compile('http://www.cnsoftnews.com/\w+/\d+/\d+.html'): CnsoftNewsLoader(),
        re.compile('china-cloud\.com/.*/\d{8}_\d+\.html'): ChinaCloudNewsLoader(),
        re.compile('http://www.cnii.com.cn/\w+/\d{4}-\d{2}/\d+/\w+.htm'): CniiComCnNewsLoader(),
        re.compile('ifeng\.com/\S+?/\d{4}/\d{4}/\d+.shtml'): IFengNewsLoader(),
        re.compile('people\.com\.cn/n/\d{4}/\d{4}/c\d+-\d+.html'): PeopleComCnNewsLoader(),
        re.compile('http://www.topoint.com.cn/html/article/\d{4}/\d+/\d+.html'): TopointNewsLoader(),
        re.compile('cbinews\.com/\S+/news/\d{4}-\d{2}-\d{2}/\d+\.htm'): CbinewsNewsLoader(),
        re.compile('http://www.ccw.com.cn/article/view/\d+'): CcwNewsLoader(),
        re.compile('\w+\.enorth.com.cn/\w+/\d{4}/\d{2}/\d{2}/|w+.shtml'): ENorthNewsLoader(),
        re.compile('gmw\.cn/\d{4}-\d{2}/\d{2}/content_\d+\.htm'): GmwNewsLoader(),
        re.compile('news.qq.com/a/\d{8}/\d+.htm'): QQNewsLoader(),
        re.compile('cbismb\.com/.*/news/\d{4}-\d{2}-\d{2}/\d+\.html'): CbismbNewsLoader(),
        re.compile('china\.com\.cn/.*/\d{8}/\d+\.shtml'): ChinaComCnNewsLoader(),
        re.compile('data\.tsci\.com\.cn/News/HTM/\d{8}/\d+.htm'): DataTsciComCnNewsLoader(),
        re.compile('.*?sohu.com/\d{8}/n\d+.shtml'): SohuNewsLoader(),
        re.compile('www\.techweb\.com\.cn/\S+/\d{4}-\d{2}-\d{2}/\d+\.shtml'): TechwebNewsLoader(),
        re.compile('\w+\.china.com/\w+/\w*/\d+/\d{8}/\d{8}_all.html'): ChinaNewsLoader(),
        re.compile('.*?sina\.com\.cn/\S+?/\d{8}/\d+\.shtml'): SinaNewsLoader(),
        re.compile('chinabyte\.com/\d+/\d+\.shtml'): ChinabyteNewsLoader()
    }

    link_extractor = LinkExtractor(
        allow=('.*'),
        allow_domains=allowed_domains
    )

    def parse(self, response):

        ret_list = []

        # 加载item
        for matcher, loader in self.matcher_loader_dict.iteritems():
            if matcher.search(response.url):
                i = loader.load(response)
                if i:
                    ret_list.append(i)

        # 添加链接
        links = [
            link.url for link in self.link_extractor.extract_links(response)
        ]
        ret_list.extend([Request(link) for link in links])

        return ret_list

