#!/bin/bash

cd /data0/sourcecode/spider/current
for i in mmsonline_com_cn_news cut35_com_news chinanfmi_com_news cnmn_com_cn_news ctia_com_cn_news jxaic_gov_cn_news jxcc_com_news jxciit_gov_cn_news jxdoftec_gov_cn_news jxdpc_gov_cn_news jxepb_gov_cn_news jxf_gov_cn_news jxgtt_gov_cn_news jxhrss_gov_cn_news jxipo_gov_cn_news jxjtc_com_news jxsl_gov_cn_news jxstc_gov_cn_news jxtc_com_cn_news jxysdzkcj_gov_cn_news cnitdc_com_news chinania_org_cn_news shmet_com_news 10jqka_com_cn_news people_com_cn_news xinhuanet_com_news cpc_people_com_cn_news ifeng_com_news sina_com_cn_news zaobao_com_news chinanews_com_finance ganzhou_gov_cn_news gz315_gov_cn_news gzciit_gov_cn_news gzdofcom_gov_cn_news gzhrss_gov_cn_news gzsczj_gov_cn_news gzsdpc_gov_cn_news gzsl_gov_cn_news gzstc_gov_cn_news sipo_gov_cn_news miit_gov_cn_news gov_cn_news ndrc_gov_cn_news most_gov_cn_news mlr_gov_cn_news chinatax_gov_cn_news chongyi_gov_cn_news ometal_com_news csu_edu_cn_news sinohongda_com_news minmetals_com_cn_news cxtc_com_news zccct_com_news chalco_com_cn_news cnsandvik_cut35_com_news jxys_org_cn_news news_smm_cn_news
do
    ~/.virtualenvs/spider/bin/scrapy crawl $i
done
